#!/bin/sh
#
###############################################################################
# sd-agent
#
# Written by Server Density <hello@serverdensity.com>
# A server monitoring daemon for www.serverdensity.com
#
# Licensed under Simplified BSD License (see LICENSE)
#
###############################################################################
#
# chkconfig: 345 85 15
# description: Server Density Monitoring Agent

### BEGIN INIT INFO
# Provides: sd-agent
# Short-Description: Start and start sd-agent
# Description: sd-agent is the monitoring agent component for Server Density
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
### END INIT INFO

# Source function library.
if [ -f /etc/init.d/functions ]; then
        . /etc/init.d/functions
fi

if [ -f /etc/SuSE-release ]; then
        . /etc/rc.status
        rc_reset
fi

PATH=$PATH:/sbin # add the location of start-stop-daemon on Debian

AGENTPATH="/usr/share/python/sd-agent/agent.py"
AGENTCONF="/etc/sd-agent/config.cfg"
AGENTUSER="sd-agent"
FORWARDERPATH="/usr/share/python/sd-agent/sdagent.py"
NAME="sd-agent"
DESC="Server Density Agent"
SUPERVISOR_PIDFILE="/var/run/sd-agent/sd-supervisord.pid"
SUPERVISOR_FILE="/etc/sd-agent/supervisor.conf"
SUPERVISOR_SOCK="/var/tmp/sd-supervisor.sock"
SUPERVISORCTL_PATH="/usr/share/python/sd-agent/bin/supervisorctl"
SUPERVISORD_PATH="/usr/share/python/sd-agent/bin/supervisord"
SYSTEM_PATH=/usr/share/python/sd-agent/bin:$PATH

if [ ! -x $AGENTPATH ]; then
    echo "$AGENTPATH not found. Exiting."
    exit 0
fi

check_status() {
    # If the socket exists, we can use supervisorctl
    if [ -e $SUPERVISOR_SOCK ]; then
        # If we're using supervisor, check the number of sd processes
        # supervisor is currently controlling, and make sure that it's the
        # same as the number of programs specified in the supervisor config
        # file:

        supervisor_processes=$(PATH=$SYSTEM_PATH $SUPERVISORCTL_PATH -c $SUPERVISOR_FILE status)

        # Number of RUNNING supervisord programs
        sd_supervisor_processes=$(echo "$supervisor_processes" |
                                       grep $NAME |
                                       grep -c RUNNING)

        # Number of expected running supervisord programs
        supervisor_config_programs=$(grep -c '\[program:' $SUPERVISOR_FILE)

        if [ "$sd_supervisor_processes" -ne "$supervisor_config_programs" ]; then
            echo "$supervisor_processes"
            echo "$DESC (supervisor) is NOT running all child processes"
            return 1
        else
            echo "$DESC (supervisor) is running all child processes"
            return 0
        fi
    else
        echo "$DESC (supervisor) is not running"
        return 1
    fi
}

# Action to take
case "$1" in
    start)
        # Could be removed during boot
        test -e /var/run/sd-agent || install -m 755 -o sd-agent -g sd-agent -d /var/run/sd-agent

        if [ ! -f $AGENTCONF ]; then
            echo "$AGENTCONF not found. Exiting."
            exit 3
        fi

        check_status > /dev/null
        if [ $? -eq 0 ]; then
            echo "$DESC is already running"
            exit 0
        fi

        su $AGENTUSER -c "$AGENTPATH configcheck" > /dev/null
        if [ $? -ne 0 ]; then
            echo "Invalid check configuration. Please run sudo /etc/init.d/sd-agent configtest for more details."
            echo "Resuming starting process."
        fi


        echo "Starting $DESC (using supervisord)" "$NAME"
        PATH=$SYSTEM_PATH daemon  --pidfile $SUPERVISOR_PIDFILE $SUPERVISORD_PATH -c $SUPERVISOR_FILE >/dev/null 2>&1
        if [ $? -ne 0 ]; then
            exit 1
        fi

        # check if the agent is running once per second for 10 seconds
        retries=10
        while [ $retries -gt 1 ]; do
          if check_status > /dev/null; then
              # We've started up successfully. Exit cleanly
              exit 0
              exit 0
          else
              retries=$(($retries - 1))
              sleep 1
          fi
        done
        # After 10 tries the agent didn't start. Report an error
        exit 1
        check_status # report what went wrong
        $0 stop
        exit 1
        ;;
    stop)

        echo "Stopping $DESC (stopping supervisord)" "$NAME"
        killproc -p $SUPERVISOR_PIDFILE $SUPERVISORD_PATH

        ;;

    info)
        shift # Shift 'info' out of args so we can pass any
              # addtional options to the real command
              # (right now only sd-agent supports additional flags)
        su $AGENTUSER -c "$AGENTPATH info $@"
        COLLECTOR_RETURN=$?
        su $AGENTUSER -c "$FORWARDERPATH info"
        FORWARDER_RETURN=$?
        exit $(($COLLECTOR_RETURN+$FORWARDER_RETURN))
        ;;

    status)
        check_status
        ;;

    restart|force-reload)
        $0 stop
        $0 start
        ;;

    configcheck)
        su $AGENTUSER -c "$AGENTPATH configcheck"
        exit $?
        ;;

    configtest)
        su $AGENTUSER -c "$AGENTPATH configcheck"
        exit $?
        ;;

    *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|info|status|configcheck|configtest}"
        exit 1
        ;;
esac

exit $?
