#!/bin/sh

set -e
#ARGS#

case "$1" in
    purge)
        rm -rf /var/run/sd-agent
        rm -rf /var/log/sd-agent
        # remove copy of the updated python binary
        rm -f /usr/share/python/sd-agent/bin/python,orig
    ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

